# Generated by Django 3.2 on 2022-08-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=50)),
                ('classnum', models.CharField(max_length=50)),
            ],
        ),
    ]
