# Generated by Django 3.2 on 2022-08-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classnet', models.BooleanField(default=False)),
                ('classnetid', models.CharField(default='', max_length=100)),
                ('classnetpw', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classnet', models.BooleanField(default=False)),
                ('classnetid', models.CharField(default='', max_length=100, unique=True)),
                ('classnetpw', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
