# Generated by Django 3.2 on 2022-08-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0002_auto_20220820_0518'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('info_id', models.IntegerField(primary_key=True, serialize=False)),
                ('professor_id', models.IntegerField()),
                ('classnum', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
