# Generated by Django 3.2 on 2022-08-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
