# Generated by Django 3.2 on 2022-08-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_info_edit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='info_id',
        ),
        migrations.AddField(
            model_name='info',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
